export const UPDATE_TRANSACTION_LIST = "UPDATE_TRANSACTION_LIST";
export const UPDATE_TRANSACTION_SELECTED = "UPDATE_TRANSACTION_SELECTED";
export const LOAD_FORM_DATA = "LOAD_FORM_DATA";
export const UPDATE_FIELD_VALUE = "UPDATE_FIELD_VALUE";
export const LOADNG_SPINNER = "LOADNG_SPINNER";
export const UPDATE_FILTER_CTRITIRAI = "UPDATE_FILTER_CTRITIRAI";
export const UPDTAE_TXN_WITH_FILTER = "UPDTAE_TXN_WITH_FILTER"